spring:
  security:
    user:
      name: changeit
      password: changeit
  main:
    allow-bean-definition-overriding: true
    banner-mode: off
  datasource:
    xa:
      data-source-class-name: org.postgresql.xa.PGXADataSource
    url: jdbc:postgresql://ebms-database:5432/ebms
    username: ebms
    password: ebms
    hikari:
      connectionTimeout: 10000
      keepaliveTime: 30000
      maxLifetime: 35000
      data-source-properties:
        networkTimeout: 60000
        # the socketTimeout property is set in seconds, NOT miliseconds!
        socketTimeout: 60

throttling:
  sql:
    combined-count: "select 
                       sum(case when em.status = 10 then 1 else 0 end) + 
                       sum(case when em.status in (11, 12, 13) and status_time >= NOW() - INTERVAL '1 SECOND' then 1 else 0 end) 
                     as total from ebms_message em where em.to_party_id = :afnemerOin"
  afnemers:
    -
      oin: 11111111111111111111
      throttleValue: 1
    -
      oin: 22222222222222222222
      throttleValue: 1
    -
      oin: 123456789012345678900001
      throttleValue: 1

logging:
  config: logback.xml

server:
  port: 8080
  error:
    include-message: always

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

