spring:
  security:
    user:
      name: changeit
      password: changeit
  main:
    allow-bean-definition-overriding: true
    banner-mode: off
  datasource:
    xa:
      data-source-class-name: org.postgresql.xa.PGXADataSource
    url: jdbc:postgresql://ebms-database:5432/ebms
    username: ebms
    password: ebms
    hikari:
      connectionTimeout: 10000
      keepaliveTime: 30000
      maxLifetime: 35000
      data-source-properties:
        networkTimeout: 60000
        # the socketTimeout property is set in seconds, NOT miliseconds!
        socketTimeout: 60

throttling:
  sql:
    combined-count: "SELECT COUNT(em.status) AS total FROM ebms_message em
                       WHERE em.to_party_id = :afnemerOin
                         AND em.status = 10
                         OR (em.status IN (11, 12, 13) AND status_time >= NOW() - INTERVAL '1 SECOND')"
  afnemers:
    -
      oin: 11111111111111111111
      throttleValue: 1
    -
      oin: 22222222222222222222
      throttleValue: 1
    -
      oin: 123456789012345678900001
      throttleValue: 1

logging:
  config: logback.xml

server:
  port: 8080
  error:
    include-message: always

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

