spring:
  main:
    allow-bean-definition-overriding: true
    banner-mode: off
  datasource:
    xa:
      data-source-class-name: org.postgresql.xa.PGXADataSource
    url: jdbc:postgresql://ebms-database:5432/ebms
    username: ebms
    password: ebms
    hikari:
      connectionTimeout: 10000
      keepaliveTime: 30000
      maxLifetime: 35000
      data-source-properties:
        networkTimeout: 60000
        # the socketTimeout property is set in seconds, NOT miliseconds!
        socketTimeout: 60
  task-executor:
    corePoolSize: 10
    maxPoolSize: 25
    queueSize: 100
  
throttling:
  sql:
    ready-to-send: "select COUNT(*) from ebms_message em where em.to_party_id = ? and status = 10"
    already-sent: "select COUNT(*) from ebms_message em where em.to_party_id = ? and status in (11, 12, 13) and status_time BETWEEN now() - (interval '1s') and now()"
  afnemers:
    -
      oin: 11111111111111111111
      throttleValue: 2
    -
      oin: 22222222222222222222
      throttleValue: 10
    -
      oin: 123456789012345678900001
      throttleValue: 1

logging:
  config: logback.xml

server:
  port: 8080
  error:
    include-message: always

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

